name: Dump
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/mirrordump/dumpyara.git

       - name: Setup Dumpyara environment
         working-directory: dumpyara
         run: |
              sudo bash setup.sh
              git config --global user.name "mirrordump"
              git config --global user.email "mirrordump@mymail.infos.st"

       - name: Setup config envs
         working-directory: dumpyara
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .githubtoken
              echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tgtoken
              echo "${{ secrets.CHAT_ID }}" > .tgchannel  #or chat group example: @box_dumps
# make sure to change git credentials as in https://github.com/mirrordump/dumpyara/commit/19016994794424b5d88c2e28add1924567b28c38
       - name: Running Dumpyara
         working-directory: dumpyara
         run: |
              ./dumpyara.sh "$ROM_URL"
#
env:
  ROM_URL: https://mega.nz/file/HyBiiL6L#G-5MTNkIkUihHX6p9LikILsXMkbUwYkn0s16QYRlBKU
