name: Dump

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              git clone --depth=1 --single-branch https://github.com/saurajbot/DumprX.git phoenix_firmware_dumper
              git clone --depth=1 --single-branch https://github.com/noobyysauraj/android_tools
              T_CID=$(cat temp/ch_id.txt)
              T_MID=$(cat temp/msg_id.txt)
              echo "$T_CID" > phoenix_firmware_dumper/.tg_cid 
              echo "$T_MID" > phoenix_firmware_dumper/.tg_mid
          
              
              
              
       - name: Setup Dumpyara environment
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash setup.sh

       - name: Setup config envs And Begin Dump
         working-directory: phoenix_firmware_dumper       
         run: |
              GITHUB_ORG_NAME="dump-sauraj"
              GITLAB_ORG_NAME="sauraj-dumps"
              GITLAB_USERNAME="ksauraj"
              GITHUB_USERNAME="saurajbot"
              GIT_CONFIG_USERNAME="ksauraj"
              GIT_CONFIG_EMAIL="rommirrorer@gmail.com"
              GIT_GITHUB_TOKEN="${{ secrets.GIT_GITHUB_TOKEN }}"
              GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}"
              TG_BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}"
              TG_CHAT_ID="@saurajdumps"
              GITLAB_HOSTNAME="gitlab.com" ## use 'gitlab.com' by default, or use your own github instance, or any public one
              echo "$GITHUB_ORG_NAME" > .github_orgname
              echo "$GITLAB_HOSTNAME" > .gitlab_instance
              echo "$GIT_GITHUB_TOKEN" > .github_token
              echo "$GITLAB_ORG_NAME" > .gitlab_orgname
              echo "$GITLAB_USERNAME" > .gitlab_username
              echo "$GITHUB_USERNAME" > .github_username
              echo "$GITLAB_TOKEN" > .gitlab_token
              echo "$TG_BOT_TOKEN" > .tg_token
              echo "$TG_CHAT_ID" > .tg_chat
              echo "1297553238" > .tg_chat_id
              export GIT_TOKEN=${{ secrets.GIT_GITHUB_TOKEN }}
              export TG_API=${{ secrets.TG_BOT_TOKEN }}
              export PUSH_TO_GITLAB=true
              export TG_TOKEN="$TG_API"
              export GIT_TKN=${{ secrets.GIT_GITHUB_TOKEN }}
              export CHAT_ID="$TG_CHAT_ID"
              export C_ID="$T_CID"
              export M_ID="$T_MID"
              #Do Not Edit This
              git config --global user.name "$GIT_CONFIG_USERNAME"
              git config --global user.email "$GIT_CONFIG_EMAIL"
              sed -i s/"DroidDumps@github.com"/"$GIT_CONFIG_EMAIL"/g dumper.sh
              sed -i s/"user.name \"DroidDumps\""/"user.name \"$GIT_CONFIG_USERNAME\""/g dumper.sh
              mkdir -p "$HOME"/dump
              mkdir -p "$HOME"/telegram
              sudo bash dumper.sh "$ROM_URL"


#######
env:
  ROM_URL: https://objects.githubusercontent.com/github-production-release-asset-2e65be/442411585/8a0f1e25-e31a-4fd8-85bd-905863fbe4e5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230207%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230207T022708Z&X-Amz-Expires=300&X-Amz-Signature=0ee7aeb60ec97eef3b8433a7cad0bb7a98d6f0603c7df52e9a27fd6f0658eca9&X-Amz-SignedHeaders=host&actor_id=47187468&key_id=0&repo_id=442411585&response-content-disposition=attachment%3B%20filename%3DPixelOS_RMX2020-13.0-20230206-1914.zip&response-content-type=application%2Foctet-stream
