name: Dump

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              git clone --depth=1 --single-branch https://github.com/saurajbot/phoenix_firmware_dumper.git
              git clone --depth=1 --single-branch https://github.com/noobyysauraj/android_tools
              T_CID=$(cat temp/ch_id.txt)
              T_MID=$(cat temp/msg_id.txt)
              echo "$T_CID" > phoenix_firmware_dumper/.tg_cid 
              echo "$T_MID" > phoenix_firmware_dumper/.tg_mid
          
              
              
              
       - name: Setup Dumpyara environment
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash setup.sh

       - name: Setup config envs And Begin Dump
         working-directory: phoenix_firmware_dumper       
         run: |
              GITHUB_ORG_NAME="dump-sauraj"
              GITLAB_ORG_NAME="sauraj-dumps"
              GITLAB_USERNAME="ksauraj"
              GITHUB_USERNAME="saurajbot"
              GIT_CONFIG_USERNAME="saurajbot"
              GIT_CONFIG_EMAIL="rommirrorer@gmail.com"
              GIT_GITHUB_TOKEN="${{ secrets.GIT_GITHUB_TOKEN }}"
              GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}"
              TG_BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}"
              TG_CHAT_ID="@saurajdumps"
              GITLAB_HOSTNAME="gitlab.com" ## use 'gitlab.com' by default, or use your own github instance, or any public one
              echo "$GITHUB_ORG_NAME" > .github_orgname
              echo "$GITLAB_HOSTNAME" > .gitlab_instance
              echo "$GIT_GITHUB_TOKEN" > .github_token
              echo "$GITLAB_ORG_NAME" > .gitlab_orgname
              echo "$GITLAB_USERNAME" > .gitlab_username
              echo "$GITHUB_USERNAME" > .github_username
              echo "$GITLAB_TOKEN" > .gitlab_token
              echo "$TG_BOT_TOKEN" > .tg_token
              echo "$TG_CHAT_ID" > .tg_chat
              echo "1297553238" > .tg_chat_id
              export GIT_TOKEN=${{ secrets.GIT_GITHUB_TOKEN }}
              export TG_API=${{ secrets.TG_BOT_TOKEN }}
              #Do Not Edit This
              git config --global user.name "$GIT_CONFIG_USERNAME"
              git config --global user.email "$GIT_CONFIG_EMAIL"
              sed -i s/"DroidDumps@github.com"/"$GIT_CONFIG_EMAIL"/g dumper.sh
              sed -i s/"user.name \"DroidDumps\""/"user.name \"$GIT_CONFIG_USERNAME\""/g dumper.sh
              mkdir -p "$HOME"/dump
              mkdir -p "$HOME"/telegram
              sudo bash dumper.sh "$ROM_URL"
              cd ../android_tools
              chmod +x setup.sh
              sudo bash setup.sh
              export GIT_TKN=${{ secrets.GIT_GITHUB_TKN }}
              export TG_API=${{ secrets.TG_BOT_TOKEN }}
              sudo ./tools/dummy_dt.sh /home/runner/work/dumper/dumper/dumped


##########
env:
  ROM_URL: https://z57nh-my.sharepoint.com/personal/sauraj_z57nh_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=9e5e0f1e-aee7-4fcf-9bc9-0f11df11602c&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvejU3bmgtbXkuc2hhcmVwb2ludC5jb21AMTI1YzZmNTItYWVlNS00MGIzLWIwOTMtYjgxNDQ3MWMzOTQwIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTY2NDI1MzY0OSIsImV4cCI6IjE2NjQyNTcyNDkiLCJlbmRwb2ludHVybCI6ImFrUC9EVjBKUXJCNkkzRll5KzFvdmt4dVpHc3c1cnNYbWVTckIyRWloZzQ9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNTciLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6IllXTmtNMkUwWkdJdE0yVXdaUzAwWVRJeUxUZzFOekV0TlRFMU1tVmhNamc1WTJaaSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJNek15WTJObE9HSXRaREZtWXkwME1EYzVMVGt4TVRRdFkyUXlNRGN4WkRJeE9UVTQiLCJhcHBfZGlzcGxheW5hbWUiOiJzYXVyYWoiLCJnaXZlbl9uYW1lIjoiU2F1cmFqIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiMzI1Nzg3ZjEtOWYyNi00NDJiLTg2YjgtMGMzZTlkNjg1Yjc4IiwidGlkIjoiMTI1YzZmNTItYWVlNS00MGIzLWIwOTMtYjgxNDQ3MWMzOTQwIiwidXBuIjoic2F1cmFqQHo1N25oLm9ubWljcm9zb2Z0LmNvbSIsInB1aWQiOiIxMDAzMjAwMUNFMUI2RTY0IiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzIwMDFjZTFiNmU2NEBsaXZlLmNvbSIsInNjcCI6ImFsbGZpbGVzLnJlYWQgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjIwLjE5MC4xNTEuMzcifQ.Rk44eWxuMjRwQVlRdTVvdGp5eVNIbUR3MEU1UzBTYUtOb3YyS09pV3NrWT0&ApiVersion=2.0
