name: Dump
 #
env:
  # Change these values if you have forked it for your own works
  GITHUB_ORG_NAME: "boxaltdump"
  GITLAB_ORG_NAME: "boxaltdumps"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  GITLAB_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
  TG_BOT_TOKEN: "${{ secrets.TG_BOT_TOKEN }}"
  TG_CHAT_ID: "@boxdumps"
  GITLAB_HOSTNAME: "https://gitgud.io"  ## use https://gitlab.com by default, or use your own github instance, or any public one
  
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              if [ -f "private.txt" ]
              then
                  git clone https://github.com/mirrordump/dumpyara.git -b private
              else
                  git clone https://github.com/mirrordump/dumpyara.git
              fi
              
       - name: Setup Dumpyara environment
         working-directory: dumpyara
         run: |
              sudo bash setup.sh
              git config --global user.name "mirrordump"
              git config --global user.email "mirrordump@mymail.infos.st"

       - name: Setup config envs
         working-directory: dumpyara
         run: |
              echo "$GITHUB_ORG_NAME" > .github_orgname
              echo "$GITHUB_TOKEN" > .github_token
              echo "$GITLAB_ORG_NAME" > .gitlab_orgname
              echo "$GITLAB_TOKEN" > .gitlab_token
              echo "$TG_BOT_TOKEN" > .tgtoken
              echo "$TG_CHAT_ID" > .tgchannel 
       - name: Running Dumpyara
         working-directory: dumpyara
         run: |
              git branch
#
env:
  ROM_URL: https://bigota.d.miui.com/V12.5.2.0.RJUIDXM/vayu_id_global_images_V12.5.2.0.RJUIDXM_20210818.0000.00_11.0_global_2eed5a738f.tgz
