name: Dump
 
  
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              if [ -f "private.txt" ]
              then
                  git clone --depth=1 --single-branch https://github.com/box-automation1/phoenix_firmware_dumper.git -b private
              else
                  git clone --depth=1 --single-branch https://github.com/box-automation1/phoenix_firmware_dumper.git
              fi
              
              
       - name: Setup Dumpyara environment
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "Box In A Box"
              git config --global user.email "evanferrao@gmail.com"

       - name: Setup config envs
         working-directory: phoenix_firmware_dumper
         run: |
              GITHUB_ORG_NAME="boxaltdump"
              GITLAB_ORG_NAME="boxaltdumps"
              GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
              GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}"
              TG_BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}"
              TG_CHAT_ID="@boxdumps"
              GITLAB_HOSTNAME="https://gitgud.io"  ## use https://gitlab.com by default, or use your own github instance, or any public one
              echo "$GITHUB_ORG_NAME" > .github_orgname
              echo "$GITHUB_TOKEN" > .github_token
              echo "$GITLAB_ORG_NAME" > .gitlab_orgname
              echo "$GITLAB_TOKEN" > .gitlab_token
              echo "$TG_BOT_TOKEN" > .tgtoken
              echo "$TG_CHAT_ID" > .tgchannel 
       - name: Running Dumpyara
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash dumper.sh "$ROM_URL"
#
env:
  ROM_URL: https://bigota.d.miui.com/V12.5.2.0.RJUIDXM/vayu_id_global_images_V12.5.2.0.RJUIDXM_20210818.0000.00_11.0_global_2eed5a738f.tgz
